[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = false
solc = "0.8.28"
evm_version = "cancun"
bytecode_hash = "none"
gas_reports = ["*"]
verbosity = 2
build_info = true
extra_output = ["storageLayout"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 119
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
